Update input and output format for bbs functions
evannetwork/vade-evan-bbs pull request #29
Opened 2023-03-30 14:00 UTC by wulfraem

## Description

Updates input and output format for bbs functions to get data format aligned to [ld-proof-vc-detail-attachment-format](https://github.com/hyperledger/aries-rfcs/blob/main/features/0593-json-ld-cred-attach/README.md#ld-proof-vc-detail-attachment-format).

## Details

- update output for offer to [ld-proof-vc-detail-attachment-format](https://github.com/hyperledger/aries-rfcs/blob/main/features/0593-json-ld-cred-attach/README.md#ld-proof-vc-detail-attachment-format)
- use offer with new format as input for request (and include it in output for it)
- use request (with offer in it) as input for issuing credential
- remove unused arguments

2023-03-31 10:23 UTC, S3bb1 requested changes

2023-03-31 10:23 UTC, S3bb1 commented on src/application/datatypes.rs
> +        credential
```suggestion
        DraftBbsCredential {
            context: vec![
                "https://www.w3.org/2018/credentials/v1".to_string(),
                "https://schema.org/".to_string(),
                "https://w3id.org/vc-revocation-list-2020/v1".to_string(),
            ],
            id: options
                .id
                .unwrap_or_else(|| format!("uuid:{}", Uuid::new_v4())),
            r#type: vec!["VerifiableCredential".to_string()],
            issuer: options.issuer_did,
            valid_until: options.valid_until,
            issuance_date: options
                .issuance_date
                .unwrap_or_else(|| get_now_as_iso_string()),
            credential_subject: CredentialSubject {
                id: options.subject_did,
                data: self // fill ALL subject data fields with empty string (mandatory and optional ones)
                    .properties
                    .clone()
                    .into_iter()
                    .map(|(name, _schema_property)| (name, String::new()))
                    .collect(),
            },
            credential_schema: CredentialSchemaReference {
                id: self.id.to_owned(),
                r#type: self.r#type.to_owned(),
            },
        }
```

can we use the direct shorthand here?

2023-03-31 10:23 UTC, S3bb1 commented on src/vade_evan_bbs.rs
> +/// Currently needs both an unsigned verifiable credential containing all the data of this verifiable credential.
```suggestion
```

can this be removed? because the unsigned vc and the nquads are removed

2023-03-31 10:23 UTC, S3bb1 commented on src/vade_evan_bbs.rs
> +    /// status to be appended to credential in offer
```suggestion
    /// status to be appended to credential in request
```

2023-03-31 10:23 UTC, S3bb1 commented on typings/vade_evan_bbs.d.ts
> +  /** status to be appended to credential in offer */
```suggestion
  /** status to be appended to credential */
```

2023-03-31 10:23 UTC, S3bb1 commented on utilities/src/test_data.rs
> +    // pub const SIGNATURE_BLINDING: &str = "RAu1jffxFGDGppIMmfDE3XSBs3oyHmi5CbPvYjKGiSo=";
```suggestion
```

2023-03-31 10:23 UTC, S3bb1 commented on utilities/src/test_data.rs
> +        "id": "743875ce-8ec0-4b6a-a67d-33a64392a5d3",
```suggestion
        "id": "uuid:743875ce-8ec0-4b6a-a67d-33a64392a5d3",
```

does this work here?

2023-03-31 10:23 UTC, S3bb1 commented on utilities/src/test_data.rs
> +        "id": "743875ce-8ec0-4b6a-a67d-33a64392a5d3",
```suggestion
        "id": "uuid:743875ce-8ec0-4b6a-a67d-33a64392a5d3",
```

2023-03-31 10:28 UTC, wulfraem commented on src/application/datatypes.rs
> +        credential
Ah, makes sense, took code as a basis, that was modifying the credential after creating the first version. :D

2023-03-31 10:43 UTC, wulfraem commented on src/vade_evan_bbs.rs
> +    /// status to be appended to credential in offer
Hm, the credential is actually in the `offer`, so `offer` made sense. From a the viewpoint of constructing the object and having a helpful description, maybe the following?

```
/// status to be appended to credential in offer (which is part of the request)
```

2023-03-31 10:43 UTC, wulfraem commented on typings/vade_evan_bbs.d.ts
> +  /** status to be appended to credential in offer */
Would align this with the description from the thread above, so will apply outcome to both. ^^

2023-03-31 10:58 UTC, wulfraem commented on utilities/src/test_data.rs
> +        "id": "743875ce-8ec0-4b6a-a67d-33a64392a5d3",
This should also work, but at the moment we're creating the proof requests with uuid's without a prefix, so we should update test data and id generation.

2023-03-31 10:58 UTC, wulfraem commented on utilities/src/test_data.rs
> +        "id": "743875ce-8ec0-4b6a-a67d-33a64392a5d3",
This should also work, but at the moment we're creating the proof requests with uuid's without a prefix, so we should update test data and id generation.

2023-04-28 13:56 UTC, S3bb1 approved these changes

2023-04-28 13:56 UTC, merged