Remove credential subject id
evannetwork/vade-evan-bbs pull request #31
Opened 2023-04-19 11:43 UTC by vineetpant

## Description
This Mr removes credential subject id from Credential and other Credential related structs (offer, credential_request e.t.c)

## Details

- Remove credential_subject.id from structs
- Adjust vade functions and other functions payload
- Adjust test cases
- Create new test data

2023-04-27 10:14 UTC, wulfraem requested changes

2023-04-27 10:14 UTC, wulfraem commented on src/application/issuer.rs
> +        let _proposal: CredentialProposal = serde_json::from_str(&EXAMPLE_CREDENTIAL_PROPOSAL)?;
Hm, do we need the `_proposal` here and in the following sections?

2023-04-27 10:14 UTC, wulfraem commented on src/application/prover.rs
> +    pub fn propose_credential(issuer_did: &str, schema_did: &str) -> CredentialProposal {
Can you update the function documentation as well? ^^

2023-04-27 10:14 UTC, wulfraem commented on utilities/src/test_data.rs
Hm, can the `SUBJECT_DID` now be removed from the test data?

2023-04-27 10:14 UTC, wulfraem commented on tests/workflows.rs
> +    let _revocation_list = create_revocation_list(&mut vade).await?;
Do we need the `_revocation_list` here?

2023-04-27 12:25 UTC, Tschuck approved these changes

2023-04-28 09:11 UTC, vineetpant commented on src/application/issuer.rs
> +        let _proposal: CredentialProposal = serde_json::from_str(&EXAMPLE_CREDENTIAL_PROPOSAL)?;
removed, it was already present earlier and throwing warnings i just fixed warnings earlier but removing it more sense :)

2023-04-28 09:11 UTC, vineetpant commented on src/application/prover.rs
> +    pub fn propose_credential(issuer_did: &str, schema_did: &str) -> CredentialProposal {
done

2023-04-28 09:12 UTC, vineetpant commented on utilities/src/test_data.rs
removed

2023-04-28 09:12 UTC, vineetpant commented on tests/workflows.rs
> +    let _revocation_list = create_revocation_list(&mut vade).await?;
removed

2023-05-02 17:13 UTC, vineetpant commented
Resolved conflicts and fixed the tests as per new changes in data types

2023-05-05 06:14 UTC, S3bb1 approved these changes

2023-05-15 11:23 UTC, merged