Feature/implement correct handling for required reveal statements in vade
evannetwork/vade-evan-bbs pull request #32
Opened 2023-05-11 11:55 UTC by vineetpant

## Description
This mr enables support for required_revealed_statements indices in Credential proof for presentation creation and verify presentation functionalities.

## Details
- Added support for required_revealed_statements in vc_zkp_offer_credential payload
- Added support for required_revealed_statements in present_proof function for presentation creation
- Added support for required_revealed_statements in verify_proof function for presentation verification
- Adjusted structs 
- Adjusted test cases

2023-05-23 12:22 UTC, Tschuck requested changes

2023-05-23 15:45 UTC, vineetpant commented on src/application/utils.rs
> +pub fn concate_required_and_reveal_statements(
done , added documentation

2023-05-24 10:59 UTC, wulfraem requested changes

2023-05-24 10:59 UTC, wulfraem commented on src/application/issuer.rs
> +    /// * `credential_status_type` - draft credential to be offered
That description looks a bit off. :D

2023-05-30 12:05 UTC, S3bb1 commented on src/application/utils.rs
> +        if required_index == 0 {
couldn't we use `check_for_requird_reveal_index0` instead of the check here?

2023-05-30 15:37 UTC, vineetpant commented on src/application/utils.rs
> +            "Invalid required_revealed_index, index 0 can't be revealed".to_owned(),
yups , changed the message :)

2023-05-30 15:38 UTC, vineetpant commented on src/application/utils.rs
> +        if required_index == 0 {
done

2023-05-30 15:38 UTC, vineetpant commented on src/application/utils.rs
> +pub fn check_for_requird_reveal_index0(
typo , fixed it thanks :)

2023-05-31 05:38 UTC, wulfraem requested changes

2023-05-31 05:38 UTC, wulfraem commented on src/application/utils.rs
> +    revealed_statements: Vec<usize>,
Not required at the moment with the current implementation, but it always feels a bit cleaner to use references (`&Vec<T>`) instead of a plain object to avoid the original object to become unavailable due to partially move.

So would it make sense to use them here? ^^

2023-05-31 05:38 UTC, wulfraem commented on src/crypto/crypto_prover.rs
> +        let all_revealed_statements = concat_required_and_reveal_statements(
Related to the comment on `concat_required_and_reveal_statements`: We should be able to remove the clones with `to_owned()` if we'd just pass references. ^^

2023-05-31 05:38 UTC, wulfraem commented on src/crypto/crypto_prover.rs
> +        let indices: HashSet<usize> = HashSet::from_iter(all_revealed_statements.iter().cloned());
As we defined `all_revealed_statements` only for the indices and don't seem to need it afterwards, we could also just pass it as is (the clone here was only to avoid the partial move, I think. ^^)

```suggestion
        let indices: HashSet<usize> = HashSet::from_iter(all_revealed_statements);
```

2023-05-31 05:38 UTC, wulfraem commented on src/vade_evan_bbs.rs
> +            let all_revealed_statements = concat_required_and_reveal_statements(
Related to the comment on `concat_required_and_reveal_statements`: We should be able to remove the clones with `to_owned()` if we'd just pass references. ^^

2023-06-01 08:45 UTC, wulfraem approved these changes

2023-06-01 08:52 UTC, Tschuck approved these changes

2023-06-01 08:52 UTC, Tschuck commented on VERSIONS.md
> +- implement handling for `required_revealed_statements` in presentaion creation and verification
```suggestion
- implement handling for `required_revealed_statements` in presentation creation and verification
```

2023-06-01 09:19 UTC, merged