Allow optional required reveal statements and credential subject ids
evannetwork/vade-evan-bbs pull request #42
Opened 2023-06-09 09:54 UTC by S3bb1

This PR makes requiredRevealStatements optional and also allows optional credential subject ids

2023-06-09 13:57 UTC, wulfraem requested changes

2023-06-09 13:57 UTC, wulfraem commented on src/vade_evan_bbs.rs
> +    #[serde(default = "empty_array")]
Should we make this field optional for `OfferCredentialPayload` in the typings? The other fields are more or less return values, so they should be okay without the optional parts.

2023-06-16 06:45 UTC, Tschuck approved these changes

2023-06-16 11:07 UTC, Tschuck approved these changes

2023-06-16 11:09 UTC, wulfraem approved these changes

2023-06-16 11:09 UTC, merged